name: DontTouchWhiteTile
version: '1.0-dev'
main: kenmizz.DontTouchWhiteTile
api-version: '1.21'
authors: [ KenMizz ]
description: Don't touch white tile

commands:
  dttt:
    description: DonTouchWhiteTile related command
    usage: "/dttt help"
    permission: command.dttt.help

permissions:
  command.dttt.set:
    default: op
  command.dttt.help:
    default: true