name: DontTouchWhiteTile
version: '1.0-dev'
main: kenmizz.DontTouchWhiteTile
api-version: '1.21'
author: KenMizz
description: Don't touch white tile, a minigame plugin

commands:
  dttt:
    description: DonTouchWhiteTile command
    usage: "/dttt help"

permissions:
  dttt.command.create:
    default: op
    description: Permission to create a DTTT Area
  dttt.command.remove:
    default: op
    description: Permission to remove a DTTT Area
  dttt.command.help:
    default: op
    description: Permission to view DTTT's help message