name: DontTouchWhiteTile
version: '1.0'
main: kenmizz.DontTouchWhiteTile
api-version: '1.21'
author: KenMizz
description: Don't touch white tile, a minigame plugin

commands:
  dttt:
    description: DonTouchWhiteTile command
    usage: "/dttt help"

permissions:
  dttt.command.create:
    default: op
    description: Permission to create a area
  dttt.command.remove:
    default: op
    description: Permission to remove a area
  dttt.command.help:
    default: op
    description: Permission to view help message
  dttt.area.break:
    default: op
    description: Permission to break block within an area
  dttt.area.place:
    default: op
    description: Permission to place block within an area